---
# GitHub Copilot Repository Configuration
# This file configures GitHub Copilot's behavior and capabilities for this repository

version: 1

# Repository information
repository:
  name: corruptvideofileinspector
  description: "A comprehensive Python CLI tool for detecting corrupted video files using FFmpeg, with optional Trakt.tv synchronization and Docker containerization support."
  language: python
  framework: cli

# Development environment
environment:
  language: Python 3.13
  package_manager: pip/poetry
  build_system: pyproject.toml
  test_framework: pytest
  linters:
    - black
    - ruff
    - mypy
  
# Available tools for agents
tools:
  bash:
    enabled: true
    description: "Execute shell commands for building, testing, and validation"
    note: "All agents can use bash if necessary for their work, even if not their primary tool"
    allowed_commands:
      - make check
      - make test
      - make format
      - make lint
      - make type
      - pytest
      - git status
      - git diff
      - git log
      - git show
      - git branch
      - git checkout
      - pre-commit
    restricted: false
  
  read:
    enabled: true
    description: "Read files from the repository"
  
  edit:
    enabled: true
    description: "Create and modify files in the repository"
  
  search:
    enabled: true
    description: "Search for patterns across the codebase"
  
  github-issues:
    enabled: true
    description: "Interact with GitHub issues (create, read, update)"
    scope: limited
  
  report_progress:
    enabled: true
    description: "Commit and push changes, update PR descriptions"

# Agents configuration
agents:
  enabled: true
  directory: .github/agents/personas
  
  available:
    - name: architecture-designer
      description: "Design system architecture and component interactions"
      use_when: "Planning system design, defining interfaces, designing data flow"
      
    - name: code-reviewer
      description: "Review code for quality, correctness, and standards"
      use_when: "Reviewing PRs, checking code quality, validating standards"
      
    - name: feature-creator
      description: "Implement new features and enhancements"
      use_when: "Building new features, adding functionality, extending APIs"
      
    - name: github-actions-troubleshooter
      description: "Debug and fix GitHub Actions workflows"
      use_when: "CI failures, workflow errors, action debugging"
      
    - name: implementation-planner
      description: "Plan implementation strategies"
      use_when: "Breaking down features, creating task lists, planning sprints"
      
    - name: issue-creation
      description: "Create and triage issues"
      use_when: "Creating issues, triaging Quick Capture submissions, formatting issues"
      
    - name: lint-error
      description: "Fix linting and formatting errors"
      use_when: "Black/Ruff/MyPy failures, code quality issues"
      
    - name: pr-conflict-resolution
      description: "Resolve pull request merge conflicts"
      use_when: "PRs have merge conflicts, need to resolve conflicts safely"
      
    - name: refactoring
      description: "Refactor code for maintainability"
      use_when: "Improving code structure, reducing complexity, modernizing code"
      
    - name: security-reviewer
      description: "Review code for security issues"
      use_when: "Security audits, checking for vulnerabilities, validating input handling"
      
    - name: test
      description: "Create and maintain tests"
      use_when: "Adding tests, fixing test failures, improving coverage"

# Skills configuration
skills:
  enabled: true
  directory: .github/agents/skills
  
  available:
    - name: issue-creation
      description: "Creating, triaging, and formatting issues"
      
    - name: pr-conflict-resolution
      description: "Resolving merge conflicts in pull requests"

# Build and test commands
commands:
  install: "make install-dev"
  build: "make check"
  test: "make test"
  lint: "make lint"
  format: "make format"
  type_check: "make type"

# Code quality standards
quality:
  line_length: 79
  type_checking: strict
  formatting: black
  linting: ruff
  
  conventions:
    - Conventional Commits
    - Single responsibility principle
    - Type annotations required
    - F-strings for formatting

# CI/CD integration
ci:
  platform: github-actions
  required_checks:
    - "Lint, Format, and Type Check"
    - "Run Tests"
    - "Build and Test Docker Image"
    - "Security Scan"

# Git and branch management
git:
  branch_protection:
    main:
      direct_push: false  # No agent can push directly to main
      require_pr: true
      require_reviews: true
  
  agent_permissions:
    can_create_branches: true  # All agents can create feature branches
    can_push_to_branches: true  # All agents can push to their own branches
    can_commit: true  # All agents can make commits
    can_create_pr: true  # All agents can create pull requests
    cannot_push_to: ["main", "production"]  # Protected branches

# Documentation
documentation:
  main: .github/copilot-instructions.md
  additional:
    - .github/instructions/instructions.md
    - .github/instructions/python.md
    - .github/instructions/testing.md
    - .github/instructions/docker.md
    - .github/instructions/git.md
    - .github/instructions/github-actions.md
