---
# GitHub Copilot Repository Configuration
# This file configures GitHub Copilot's behavior and capabilities for this repository

version: 1

# Repository information
repository:
  name: corruptvideofileinspector
  description: "A comprehensive Python CLI tool for detecting corrupted video files using FFmpeg, with optional Trakt.tv synchronization and Docker containerization support."
  language: python
  framework: cli

# Development environment
environment:
  language: Python 3.13
  package_manager: pip/poetry
  build_system: pyproject.toml
  test_framework: pytest
  linters:
    - black
    - ruff
    - mypy
  
# Available tools for agents
tools:
  bash:
    enabled: true
    description: "Execute shell commands for building, testing, and validation"
    allowed_commands:
      - make check
      - make test
      - make format
      - make lint
      - make type
      - pytest
      - git status
      - git diff
      - pre-commit
    restricted: false
  
  read:
    enabled: true
    description: "Read files from the repository"
  
  edit:
    enabled: true
    description: "Create and modify files in the repository"
  
  search:
    enabled: true
    description: "Search for patterns across the codebase"
  
  github-issues:
    enabled: true
    description: "Interact with GitHub issues (create, read, update)"
    scope: limited
  
  report_progress:
    enabled: true
    description: "Commit and push changes, update PR descriptions"

# Agents configuration
agents:
  enabled: true
  directory: .github/agents
  
  available:
    - architecture-designer
    - code-reviewer
    - feature-creator
    - implementation-planner
    - issue-creation-agent
    - issue-creation
    - lint-error
    - pr-conflict-resolution
    - refactoring
    - security-reviewer
    - test

# Skills configuration
skills:
  enabled: true
  directory: .github/skills
  
  available:
    - issue-creation
    - pr-conflict-resolution

# Build and test commands
commands:
  install: "make install-dev"
  build: "make check"
  test: "make test"
  lint: "make lint"
  format: "make format"
  type_check: "make type"

# Code quality standards
quality:
  line_length: 79
  type_checking: strict
  formatting: black
  linting: ruff
  
  conventions:
    - Conventional Commits
    - Single responsibility principle
    - Type annotations required
    - F-strings for formatting

# CI/CD integration
ci:
  platform: github-actions
  required_checks:
    - "Lint, Format, and Type Check"
    - "Run Tests"
    - "Build and Test Docker Image"
    - "Security Scan"

# Documentation
documentation:
  main: .github/copilot-instructions.md
  additional:
    - .github/instructions/instructions.md
    - .github/instructions/python.md
    - .github/instructions/testing.md
    - .github/instructions/docker.md
    - .github/instructions/git.md
    - .github/instructions/github-actions.md
