logging:
  level: INFO
  file: /tmp/inspector.log
ffmpeg:
  command: /usr/bin/ffmpeg
  quick_timeout: 30
  deep_timeout: 1800
processing:
  max_workers: 8
  default_mode: "quick"
output:
  default_json: true
  default_output_dir: /tmp/output
  default_filename: "scan_results.json"
scan:
  recursive: true
  max_workers: 8
  mode: "quick"
  default_input_dir: /tmp/videos
  extensions: [".mp4", ".mkv", ".avi", ".mov", ".wmv", ".flv"]
trakt:
  client_id: ""
  client_secret: ""
  include_statuses: ["healthy"]