---
name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.2.3)'
        required: true
        type: string
      draft:
        description: 'Create as draft release'
        required: false
        type: boolean
        default: false
      prerelease:
        description: 'Mark as pre-release'
        required: false
        type: boolean
        default: false

jobs:
  # Build release artifacts using reusable workflow
  # This includes Python package build, Docker multi-platform build,
  # and optional publishing to PyPI and Docker Hub
  build-release:
    name: Build Release Artifacts
    uses: ./.github/workflows/actions/build.yml
    with:
      python-version: ${{ vars.DEFAULT_PYTHON_VERSION }}
      build-python: true
      build-docker: true
      docker-platforms: 'linux/amd64,linux/arm64'  # Multi-platform support for broad compatibility
      docker-push: true
      tag-name: ${{ github.event.inputs.tag || github.ref_name }}
      upload-pypi: true
      docker-username: ${{ vars.DOCKER_USERNAME }}
    secrets:
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
      pypi-token: ${{ secrets.PYPI_API_TOKEN }}

  # Run comprehensive security scanning on release artifacts
  # Includes dependency scanning, code analysis, and Docker image vulnerability scanning
  release-security-scan:
    name: Release Security Scan
    uses: ./.github/workflows/actions/security-scan.yml
    with:
      scan-dependencies: true
      scan-code: true
      scan-docker: true
      docker-image: '${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.event.inputs.tag || github.ref_name }}'

  # Create GitHub Release with generated changelog and artifacts
  # Only runs if both build and security scan succeed
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-release, release-security-scan]
    # Always evaluate needs, but only run if both jobs succeeded
    if: always() && needs.build-release.result == 'success' && needs.release-security-scan.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release tag
        id: tag
        run: |
          # Determine release tag from manual input or git tag event
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate changelog
        id: changelog
        run: |
          set -e
          # Generate changelog from git commits since last tag
          # If no previous tag exists, include all commits in the repository
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -n "$LAST_TAG" ]; then
            CHANGELOG=$(git log "${LAST_TAG}..HEAD" --pretty=format:"- %s (%h)" --no-merges)
          else
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" --no-merges)
          fi

          # Save changelog to GitHub Actions output using heredoc syntax for multiline content
          {
            echo "changelog<<EOF"
            echo "$CHANGELOG"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Download Python artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-packages-${{ steps.tag.outputs.tag }}
          path: ./dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@latest
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          body: |
            ## Changes

            ${{ steps.changelog.outputs.changelog }}

            ## Docker Images

            ```bash
            docker pull ${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.tag.outputs.tag }}
            docker pull ${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ```

            ## Python Package

            ```bash
            pip install ${{ github.event.repository.name }}==${{ steps.tag.outputs.tag }}
            ```

            ## Verification

            - ✅ All tests passed
            - ✅ Security scans completed
            - ✅ Docker images built for linux/amd64, linux/arm64
            - ✅ Python package published to PyPI
          draft: ${{ github.event.inputs.draft || false }}
          prerelease: ${{ github.event.inputs.prerelease || false }}
          files: ./dist/*
          # Allow GitHub to automatically generate additional release notes
          generate_release_notes: true

  # Post-release summary and notifications
  # Provides a summary of completed release actions for monitoring and logging
  post-release:
    name: Post-release Actions
    runs-on: ubuntu-latest
    needs: create-release
    # Only run if release creation succeeded
    if: always() && needs.create-release.result == 'success'
    steps:
      - name: Post-release summary
        run: |
          set -e
          echo "🎉 Release ${{ github.event.inputs.tag || github.ref_name }} completed successfully!"
          echo "- GitHub Release: Created"
          echo "- Docker Images: Published"
          echo "- PyPI Package: Published"
          echo "- Security Scans: Passed"
