blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/tdorsey/corruptvideofileinspector/discussions
    about: Ask questions, share ideas, and discuss the project with the community
  - name: 📖 Documentation
    url: https://github.com/tdorsey/corruptvideofileinspector/tree/main/docs
    about: Read the comprehensive documentation for detailed guidance