name: 🚀 Feature Request
description: Request a new feature or enhancement
title: "[FEAT]: "
labels: ["feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please provide as much detail as possible to help us understand your needs.
        
        **Title Examples:**
        - `feat(cli): add new scan mode for faster processing`
        - `feat(scanner): implement parallel video analysis`
        - `feat(trakt): add support for custom collections`
        - `feat(config): support environment variable configuration`
        - `feat(output): add CSV export format support`
        
        **Component labels will be automatically applied** based on your selection below.

  - type: dropdown
    id: stakeholder
    attributes:
      label: Stakeholder Type
      description: What type of stakeholder are you?
      options:
        - Project Maintainer
        - Contributor
        - End User
      default: 0
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component/Domain
      description: Which component or domain does this feature request affect?
      options:
        - CLI
        - Scanner
        - Trakt Integration
        - Config
        - Reporter
        - Output
        - Docker
        - CI/CD
        - GitHub Actions
        - Tests
        - Documentation
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: user-story-want
    attributes:
      label: "I want to"
      description: "Describe what you want to achieve"
      placeholder: "I want to be able to..."
    validations:
      required: true

  - type: textarea
    id: user-story-but
    attributes:
      label: "But"
      description: "Describe any challenge or obstacle you're facing"
      placeholder: "But currently I cannot because..."
    validations:
      required: true

  - type: textarea
    id: user-story-helps
    attributes:
      label: "This helps by"
      description: "Explain the benefit this feature would provide"
      placeholder: "This helps by enabling..."
    validations:
      required: true

  - type: textarea
    id: user-story-unlike
    attributes:
      label: "Unlike"
      description: "Describe how this differs from alternatives"
      placeholder: "Unlike existing solutions that..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any additional information that might be helpful...

