name: ⚡ Performance Issue
description: Report performance problems or request optimizations
title: "[PERF]: "
labels: ["performance"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve performance! Please provide details about the performance issue or optimization request.
        
        **Title Examples:**
        - `perf(scanner): optimize video analysis algorithm for large files`
        - `perf(cli): reduce memory usage during batch processing`
        - `perf(trakt): improve API call efficiency and caching`
        - `perf(config): speed up configuration loading and validation`
        - `perf(output): optimize report generation for large datasets`
        
        **Component labels will be automatically applied** based on your selection below.

  - type: dropdown
    id: stakeholder
    attributes:
      label: Stakeholder Type
      description: What type of stakeholder are you?
      options:
        - Project Maintainer
        - Contributor
        - End User
      default: 0
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component/Domain
      description: Which component or domain has performance issues?
      options:
        - CLI
        - Scanner
        - Trakt Integration
        - Config
        - Reporter
        - Output
        - Docker
        - CI/CD
        - GitHub Actions
        - Tests
        - Documentation
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: user-story-want
    attributes:
      label: "I want to"
      description: "Describe the performance improvement you need"
      placeholder: "I want the application to run faster when..."
    validations:
      required: true

  - type: textarea
    id: user-story-but
    attributes:
      label: "But"
      description: "Describe the current performance problem"
      placeholder: "But currently it takes too long to..."
    validations:
      required: true

  - type: textarea
    id: user-story-helps
    attributes:
      label: "This helps by"
      description: "Explain how better performance would help"
      placeholder: "This helps by reducing wait time and..."
    validations:
      required: true

  - type: textarea
    id: user-story-unlike
    attributes:
      label: "Unlike"
      description: "Describe how this differs from current performance"
      placeholder: "Unlike the current slow processing which..."
    validations:
      required: true

  - type: dropdown
    id: performance-type
    attributes:
      label: Performance Issue Type
      description: What type of performance issue is this?
      options:
        - Slow execution/processing
        - High memory usage
        - High CPU usage
        - Slow startup time
        - Network latency
        - File I/O bottleneck
        - Database/API calls
        - Algorithm inefficiency
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: current-performance
    attributes:
      label: Current Performance
      description: Describe the current performance metrics or timings
      placeholder: |
        Examples:
        - Scanning 100 files takes 15 minutes
        - Memory usage reaches 2GB during processing
        - Application startup takes 30 seconds
        - API calls timeout frequently

  - type: textarea
    id: expected-performance
    attributes:
      label: Expected Performance
      description: What performance would you expect or need?
      placeholder: |
        Examples:
        - Should scan 100 files in under 5 minutes
        - Memory usage should stay under 500MB
        - Startup should take less than 5 seconds

  - type: textarea
    id: test-environment
    attributes:
      label: Test Environment
      description: Describe your testing environment and conditions
      placeholder: |
        - Hardware: [e.g., 4 CPU cores, 8GB RAM]
        - OS: [e.g., Ubuntu 22.04]
        - File count/size: [e.g., 1000 video files, 500MB each]
        - Other relevant conditions

  - type: textarea
    id: profiling-data
    attributes:
      label: Profiling Data (Optional)
      description: If you have any profiling data or performance measurements, please share
      render: text

