name: Security Issue
description: Report a security vulnerability or concern.
labels:
  - security
assignees: []
body:
  - type: checkboxes
    id: domain
    attributes:
      label: Security Domain
      description: Select the relevant security domain(s).
      options:
        - label: Docker/Container
        - label: Secrets/Environment Variables
        - label: Dependency Vulnerability
        - label: Input Validation
        - label: Other (describe below)
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security issue, vulnerability, or concern in detail.
      placeholder: Enter a detailed description of the security issue.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: If applicable, provide steps to reproduce the issue.
      placeholder: List the steps to reproduce the issue.
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Explain the potential impact or risk.
      placeholder: Describe the impact or risk.
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: (Optional) Suggest a fix or mitigation.
      placeholder: Suggest a solution or mitigation.
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, logs, or screenshots here.
      placeholder: Additional context, logs, or screenshots.
