# Example Configuration for Corrupt Video Inspector
# Copy this to config.local.yaml and customize as needed
# Local config files are ignored by git for security

# Logging configuration
logging:
  level: "DEBUG"  # Change to DEBUG for detailed logs
  format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file: "/app/output/inspector.log"  # Log to file instead of console

# FFmpeg configuration  
ffmpeg:
  command: "/usr/bin/ffmpeg"  # Specify custom ffmpeg path if needed
  quick_timeout: 30  # Reduce timeout for faster quick scans
  deep_timeout: 1800  # Increase timeout for thorough deep scans (30 minutes)

# Processing configuration
processing:
  max_workers: 8  # Increase for more parallel processing
  default_mode: "quick"  # Default to quick scans

# Output configuration
output:
  default_json: true  # Always generate JSON output
  default_output_dir: "/app/output"
  default_filename: "corruption_scan.json"

# File scanning configuration
scan:
  recursive: true
  default_input_dir: "/app/videos"  # Default directory to scan if none provided
  extensions:
    - ".mp4"
    - ".mkv" 
    - ".avi"
    - ".mov"
    # Add more formats as needed
    - ".wmv"
    - ".flv"

# Secrets configuration
secrets:
  docker_secrets_path: "/run/secrets"