name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  # First job: Get available labels using the reusable workflow
  get-labels:
    uses: ./.github/workflows/internal/get-labels.yml

  validate-pr-title:
    name: Validate PR Title and Requirements
    runs-on: ubuntu-latest
    needs: get-labels

    steps:
      - name: Validate PR title format
        id: semantic-pr
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Define the allowed conventional commit types based on the
          # project's issue templates
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
          # Allow scopes (optional part after type)
          requireScope: false
          # Disallow release-related types since this is handled by
          # automated releases
          disallowScopes: |
            release
          # Validate that the subject starts with lowercase
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            starts with a lowercase letter.
          # Ignore merge commits and dependabot PRs
          ignoreLabels: |
            bot
            ignore-semantic-pr
          # Validate PR body contains issue reference
          validateSingleCommit: false

      - name: Validate issue reference
        id: issue-validation
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const body = context.payload.pull_request.body || '';
            const branchName = context.payload.pull_request.head.ref || '';

            // Check for issue reference in title, body, or branch name
            const issueRefPattern = /#(\d+)/;
            const branchIssuePattern = /(?:issue-|fix-|feature-|bug-|hotfix-)(\d+)/i;
            let foundIssueNumber = null;

            // Try to extract issue number from title
            let match = title.match(issueRefPattern);
            if (match) {
              foundIssueNumber = match[1];
            }
            // Try to extract from body if not found
            if (!foundIssueNumber) {
              match = body.match(issueRefPattern);
              if (match) {
                foundIssueNumber = match[1];
              }
            }
            // Try to extract from branch name if not found
            if (!foundIssueNumber) {
              match = branchName.match(issueRefPattern);
              if (match) {
                foundIssueNumber = match[1];
              } else {
                match = branchName.match(branchIssuePattern);
                if (match) {
                  foundIssueNumber = match[1];
                }
              }
            }

            const hasIssueReference = Boolean(foundIssueNumber);

            // Validate that the referenced issue exists
            let issueExists = false;
            if (foundIssueNumber) {
              try {
                const issue = await github.rest.issues.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: parseInt(foundIssueNumber, 10)
                });
                if (issue && issue.status === 200) {
                  issueExists = true;
                }
              } catch (error) {
                issueExists = false;
              }
            }

            // Set outputs for the next step
            core.setOutput('has_issue_reference', hasIssueReference);
            core.setOutput('issue_exists', issueExists);
            core.setOutput('found_issue_number', foundIssueNumber || '');

            console.log(`Issue reference validation:`);
            console.log(`- Has reference: ${hasIssueReference}`);
            console.log(`- Issue exists: ${issueExists}`);
            if (foundIssueNumber) {
              console.log(`- Found issue: #${foundIssueNumber}`);
            }

      - name: Handle validation results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const isDraft = context.payload.pull_request.draft;

            // Get results from previous steps
            const semanticPrFailed = '${{ steps.semantic-pr.outcome }}' === 'failure';
            const hasIssueReference = '${{ steps.issue-validation.outputs.has_issue_reference }}' === 'true';
            const issueExists = '${{ steps.issue-validation.outputs.issue_exists }}' === 'true';
            const foundIssueNumber = '${{ steps.issue-validation.outputs.found_issue_number }}';

            let validationErrors = [];

            // Collect validation errors
            if (semanticPrFailed) {
              validationErrors.push('❌ **PR title format validation failed**');
              validationErrors.push('   The PR title must follow conventional commit format: `type: description`');
              validationErrors.push('   Allowed types: `feat`, `fix`, `docs`, `style`, `refactor`, `perf`, `test`, `chore`');
              validationErrors.push('   Example: `feat: add new video validation feature`');
            }

            if (!hasIssueReference) {
              validationErrors.push('❌ **Missing issue reference**');
              validationErrors.push('   PR must reference an issue number (e.g., #123) in the title, body, or branch name');
              validationErrors.push('   Example: `feat: add new feature (#123)` or add "Fixes #123" to PR body, or use a branch name like `issue-123-description`');
            } else if (!issueExists) {
              validationErrors.push('❌ **Referenced issue does not exist**');
              validationErrors.push(`   Issue #${foundIssueNumber} was not found in this repository. Please reference a valid, existing issue.`);
            }

            // If there are validation errors, handle the failure
            if (validationErrors.length > 0) {
              // Create comment with validation errors
              const errorList = validationErrors.join('\n');
              const commentBody = `## 🚫 PR Validation Failed

            This pull request will be automatically converted to **draft** and labeled due to validation failures.

            ### Issues Found:
            ${errorList}

            ### How to Fix:
            1. **Fix the PR title format** if needed:
               - Use conventional commit format: \`type: description\`
               - Ensure description starts with lowercase letter
               - Allowed types: \`feat\`, \`fix\`, \`docs\`, \`style\`, \`refactor\`, \`perf\`, \`test\`, \`chore\`

            2. **Add issue reference** if missing:
               - Include issue number in title: \`feat: add new feature (#123)\`
               - Or add to PR body: \`Fixes #123\` or \`Closes #123\`

            3. **Mark as ready for review** once all issues are resolved

            ---
            *This check is automated. Once you fix the issues above, the validation will run again when you update the PR.*`;

              try {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  body: commentBody
                });
                console.log('✅ Posted validation failure comment');
              } catch (error) {
                console.error('❌ Failed to post comment:', error.message);
              }

              // Fail the workflow so the failure job can handle labels and draft conversion
              core.setFailed('PR validation failed. Check the comments for details.');
              return;
            }

            // Success case
            console.log('✅ All validations passed');
            if (hasIssueReference && foundIssueNumber) {
              console.log(`✅ Issue reference found and validated: #${foundIssueNumber}`);
            }

            // Post success comment for draft PRs
            if (isDraft) {
              const validatedItems = [
                '- ✅ PR title follows conventional commit format',
                '- ✅ Issue reference found and validated'
              ];

              const successComment = `## ✅ PR Validation Passed

            All validation checks have passed! This PR is ready for review.

            ### Validated:
            ${validatedItems.join('\n')}

            You can now mark this PR as ready for review, or it will be automatically promoted.`;

              try {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  body: successComment
                });
                console.log('✅ Posted validation success comment for draft PR');
              } catch (error) {
                console.error('❌ Failed to post success comment:', error.message);
              }
            }

  # Job to handle validation failure - add failure labels and convert to draft
  handle-validation-failure:
    name: Handle Validation Failure
    runs-on: ubuntu-latest
    needs: [get-labels, validate-pr-title]
    if: always() && needs.validate-pr-title.result == 'failure'
    steps:
      - name: Add validation failure labels and convert to draft
        uses: ./.github/workflows/internal/manage-pr.yml
        with:
          pr_number: '${{ github.event.pull_request.number }}'
          labels_add: '["validation:failed", "status:draft", "needs:attention"]'
          labels_remove: '["validation:passed", "status:ready"]'
          pr_state: 'draft'

  # Job to handle validation success - add success labels
  handle-validation-success:
    name: Handle Validation Success
    runs-on: ubuntu-latest
    needs: [get-labels, validate-pr-title]
    if: always() && needs.validate-pr-title.result == 'success'
    steps:
      - name: Add validation success labels
        uses: ./.github/workflows/internal/manage-pr.yml
        with:
          pr_number: '${{ github.event.pull_request.number }}'
          labels_add: '["validation:passed"]'
          labels_remove: '["validation:failed", "needs:attention"]'

  # Job to handle when PR becomes ready after being draft due to validation
  promote-from-draft:
    name: Promote Draft PR to Ready
    runs-on: ubuntu-latest
    needs: [get-labels, validate-pr-title]
    if: always() && needs.validate-pr-title.result == 'success' && github.event.pull_request.draft == true
    steps:
      - name: Add ready-for-review labels and suggest promotion
        uses: ./.github/workflows/internal/manage-pr.yml
        with:
          pr_number: '${{ github.event.pull_request.number }}'
          labels_add: '["validation:passed", "status:ready-for-promotion"]'
          labels_remove: '["validation:failed", "status:draft", "needs:attention"]'
