name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Release Artifacts
    uses: ./.github/workflows/actions/build.yml
    with:
      python-version: ${{ vars.PYTHON_VERSION || '3.13' }}
      build-python: true
      build-docker: true
      docker-platforms: 'linux/amd64,linux/arm64'
      docker-push: true
      docker-username: ${{ vars.DOCKER_USERNAME }}
      tag-name: ${{ github.ref_name }}
      upload-pypi: true
    secrets:
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
      pypi-token: ${{ secrets.PYPI_API_TOKEN }}

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
